server:
  port: 8082

spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://localhost:5444/fraud
    password: password
    username: myjavablog
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


